### ISSUE TITLE
Finalize Doc Structure

### ISSUE THREAD

**Issue by therealmolf** [timaeus-research/devinterp#41]
### Finalize Documentation Structure

This issue links to #35 .

### Description
--- 
The devinterp repository requires documentation. Yet, there is no existing documentation structure for the repository. This constrains the progress to be made for the creation of the docs. Hence, finalizing the doc structure should be prioritized so that contributors can start improving docstrings, adding examples, etc.

### Tasks
---
- [ ] Choose the final documentation structure
- It has been suggested to follow this format:
![image](https://github.com/timaeus-research/devinterp/assets/41650155/d25192af-29ad-4d11-a2d9-abe2e0005ed6)
- Alternatively, there is the [Diataxis framework](https://diataxis.fr)
- [ ] Finalize preferred format for docstrings of the package, module, class, function, etc.
- Personally, I find Google-style format the most understandable. Moreover, this is supported by both Sphinx and mkdocs. Check [this](https://gist.github.com/redlotus/3bc387c2591e3e908c9b63b97b11d24e) for how it looks like.
- [ ] Start creating the docs (Related tasks should be linked to #35 and not this current issue)

**Comment by madvid** [comment]
Great @therealmolf,
The structure suggested come from diataxis consideration:
* tutorials -> obvious reference to tutorial section in the frameworks
* used guide -> contains the how-to-guides
* developpers -> guidelines for specific contributions -> how to add a new sampling method, how to add a new .. etc
* functions -> could another name but it concerns the explanation part and should answer to "what is ..."

For the issue you should also consider the following section:
* Acceptance Criteria 
* Definition of Done
